### ISSUE TITLE
"/query/:_id" cannot be navigated direclty

### ISSUE THREAD

**Issue by konard** [linksplatform/Crawler#11]
For example:
http://localhost:3000/query/HEyhcEfuck6dThnNL
ends up with:
![2016-03-14 12-58-12](https://cloud.githubusercontent.com/assets/1431904/13740942/731425ca-e9e4-11e5-8543-b14024565776.png)

https://github.com/linksplatform/Crawler/blob/master/MeteorUI/crawler.js#L263

**Comment by ivansglazunov** [comment]
crawler.js#266... `q` is not founded... `q.value` is undefined. Page will work again.

**Comment by konard** [comment]
Yes, but why if I click on the link inside application it is working. If I copy the same link to other browser tab and go to it direcly it returns undefined, but id is the same symbol to symbol. And query document is still in Mongo's collection.

**Comment by ivansglazunov** [comment]
Two-stage loading templates and paths. First load without variables. You must check `q` document.

``` js
if (q) {} else {}
```

On route loading collections not yet loaded.

**Comment by ivansglazunov** [comment]
Client collection waiting for a response from the server with the characteristics of the available cursor from this collection. Where there is chance for nonexists variable it should always be verified.

**Comment by konard** [comment]
So how to wait until collections are loaded? Or it is a better solution to move all data to template's helpers?

**Comment by ivansglazunov** [comment]
No. Just check `if (q)`

**Comment by ivansglazunov** [comment]
It calls twise

**Comment by ivansglazunov** [comment]
On data changed/added/removed templates with dependence to it redrawing.

**Comment by ivansglazunov** [comment]
First time templates draw without data.

**Comment by ivansglazunov** [comment]
It is JS - if you not write condition - no typing, no constant required data.

**Comment by konard** [comment]
Why here (http://iron-meteor.github.io/iron-router/#rendering-templates-with-data) they don't make any checks?

**Comment by ivansglazunov** [comment]
Because data returns directly. `undefined` or `Document`. Your error in JS, before you return data to template. Tempalte reacting to change result (`undefined`/`Document`) but in JS you call variable `q`. `q == undefined`. Thrown error...

**Comment by konard** [comment]
> No. Just check if (q)

So what to return, if no q is there? Nothing, undefined, null?

**Comment by ivansglazunov** [comment]
No return == return undefined

**Comment by ivansglazunov** [comment]
You can open skype? I need an advice.

**Comment by Konard** [comment]
> No return == return undefined

**Comment by konard** [comment]
> No return == return undefined

So it is ok to return undefined from Iron Router? So template will get data twice, undefined, then real value, and the real value will be last, so it will be rendered?

> You can go open skype? I need an advice.

Yes, calling you.

**Comment by ivansglazunov** [comment]
Last result.
